### ISSUE TITLE
Attachment uploads are broken with Promotions

### ISSUE THREAD

**Issue by neiljohari** [Syosset/syosset#110]
https://sentry.io/syosset/syossethscom/issues/456025498/

```
NameError: wrong constant name 
  app/controllers/attachments_controller.rb:12:in `get_attachable'
    @attachable = params[:attachable_type].classify.constantize.find(params[:attachable_id])
  app/controllers/application_controller.rb:65:in `set_current_user'
    yield
...
(69 additional frame(s) were not displayed)

NameError: wrong constant name 
```

**Comment by neiljohari** [comment]
I think the fix is just to `include Concerns::Attachable` in the Promotion model
